### PR TITLE
#127 Refactor Read method on boundaryReader to avoid usage of UnreadByte()

### LINKED ISSUE #127: boundary_test failures under Go 1.12.1
What I did:

Run unit tests with `go version go1.12.1 linux/amd64`

What I expected:

Success!

What I got:

```
--- FAIL: TestBoundaryReader (0.00s)
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE\r\nafter", want: "\r\n--STOPHERE\r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE\t\r\nafter", want: "\r\n--STOPHERE\t\r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE--\r\nafter", want: "\r\n--STOPHERE--\r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE \t\r\nafter", want: "\r\n--STOPHERE \t\r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE--\t \r\nafter", want: "\r\n--STOPHERE--\t \r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE--\r\nafter", want: "\r\n--STOPHERE--\r\nafter"
    boundary_test.go:95: Rest of reader:
        got: "\n--STOPHERE--\r\nafter", want: "\r\n--STOPHERE--\r\nafter"
FAIL
FAIL	github.com/jhillyerd/enmime	1.556s
```

Release or branch I am using: `develop`

https://travis-ci.org/jhillyerd/enmime/jobs/513790838

### PR DESCRIPTION
**Pull request by requaos**
Resolves #127 
Actually I like this solution more, since the line-count has gone down

### CODE REVIEW

File: boundary.go [hunk 1]
```diff
@@ -82,35 +82,33 @@ func (b *boundaryReader) Read(dest []byte) (n int, err error) {
...
+				padding = 2
+				check = true
 			// Check for line feed as potential LF boundary prefix.
 			case '\n':
-				peek, err := b.r.Peek(len(b.nlPrefix) + 2)
+				check = true
+			}
+
+			if check {
+				check = false
```
Comment (golangcibot) [inline boundary.go]: ineffectual assignment to `check` (from `ineffassign`)

**Comment by requaos** [comment]
@jhillyerd This is in a ready-to-merge state

**Comment by jhillyerd** [comment]
Thanks so much, I'll merge into the featre branch, watch tests, then merge into develop when I get a chance.
