### PR TITLE
Fix linter issues

### LINKED ISSUE #241: PR checks fail
https://github.com/jhillyerd/enmime/blob/master/.github/workflows/pull-checks.yml is trying to use go 1.17 packages on 1.13 and failing

### PR DESCRIPTION
**Pull request by lcd1232**
Fixes #241

### CODE REVIEW

File: header.go [hunk 1]
```diff
@@ -21,13 +21,13 @@ const (
 	cdInline     = "inline"
 
 	// Standard MIME content types
-	ctAppPrefix        = "application/"
+	ctAppPrefix        = "application/" //nolint
```
Comment (lcd1232) [inline header.go:24]: @jhillyerd I need your decision on what to do with the unused code.

File: encode.go [hunk 2]
```diff
@@ -36,9 +36,13 @@ func (p *Part) Encode(writer io.Writer) error {
 	cte := p.setupMIMEHeaders()
 	// Encode this part.
 	b := bufio.NewWriter(writer)
-	p.encodeHeader(b)
+	if err := p.encodeHeader(b); err != nil {
+		return err
+	}
 	if len(p.Content) > 0 {
-		b.Write(crnl)
+		if _, err := b.Write(crnl); err != nil {
```
Comment (jhillyerd) [inline encode.go:43]: for all of the b.Writes in this func, it doesn't matter if they fail, as it will cause the b.Flush at the end to fail.  can we do a `_, _ :=` instead to remove the iferr noise?  Or disable linting in this part?  It makes it really hard to read.

File: header.go (hunk 1 above)
Comment (jhillyerd) [reply header.go:24]: I think we can just delete these, seems unlikely we will use them.

**Review by jhillyerd — CHANGES_REQUESTED** [review]

File: header.go (hunk 1 above)
Comment (lcd1232) [reply header.go]: Done

File: encode.go (hunk 2 above)
Comment (lcd1232) [reply encode.go:43]: I'm not sure that we can ignore these errors because `bufio.NewWriter` can be changed in the future and `b.Flush` will not check previous errors. What do you think?

Comment (jhillyerd) [reply encode.go:43]: That's not correct, because Flush() does not exist on other writers, so it will be obvious if the writer type were to be changed.

Comment (jhillyerd) [reply encode.go:43]: Will resolve this for now, I'd like to submit this PR so that other PRs don't have to deal with the linter errors.

**Review by jhillyerd — APPROVED** [review]

**Comment by jhillyerd** [comment]
Thanks!
