### PR TITLE
fix: Handle spaces inside angle brackets

### LINKED ISSUE #339: Possible to handle these `From:` values?
I got messages with `From:` like this:
```
From: Name< user@domain.com >
From: Name <sales@a.com >
```
Both report `unclosed angle-addr` error, but MUAs work fine.

I wonder whether we can handle this in enmime. :)

### PR DESCRIPTION
**Pull request by dflse**
closes #339

### CODE REVIEW

File: internal/stringutil/addr.go [hunk 1]
```diff
@@ -74,13 +88,19 @@ func EnsureCommaDelimitedAddresses(s string) string {
...
+				if r == ' ' && !inAngles {
 					inDomain = false
 					sb.WriteRune(',')
 					sb.WriteRune(r)
 					continue
 				}
 			}
+
+			if inAngles {
+				if r == ' ' {
```
Comment (jhillyerd) [inline internal/stringutil/addr.go:100]: Could just use `&&` for these two ifs

**Review by jhillyerd — CHANGES_REQUESTED** [review]
Looks good, one change

**Review by jhillyerd — APPROVED** [review]

**Comment by jhillyerd** [comment]
Thanks!

**Comment by iredmail** [comment]
Thanks @dflse :)
